package steps;

import io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import static io.restassured.RestAssured.when;
import io.restassured.response.Response;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Map;
import java.util.HashMap;
import java.io.IOException;
import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.When;
import io.cucumber.java.en.Then;
import io.cucumber.java.After;
import io.cucumber.java.en.And;
import static org.junit.Assert.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.hamcrest.Matchers.*;

public class ToDoSteps {
    private Process serviceProcess;
    private String projectId;

    @Given("the service is running")
    public void serviceRunning() {
        RestAssured.baseURI = "http://localhost:4567";
        if (isServiceRunning()) {
            try {
                given().when().get("/shutdown");
            } catch (Exception e) {
            }
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            startService();
        } else {
            startService();
        }
    }

    private boolean isServiceRunning() {
        try {
            URL serviceUrl = new URL("http://localhost:4567");
            HttpURLConnection serviceConnection = (HttpURLConnection) serviceUrl.openConnection();
            serviceConnection.setRequestMethod("GET");
            serviceConnection.connect();
            int serviceResponseCode = serviceConnection.getResponseCode();

            return serviceResponseCode == 200;
        } catch (IOException e) {
            return false;
        }
    }

    private void startService() {
        try {
            serviceProcess = new ProcessBuilder("java", "-jar", "runTodoManagerRestAPI-1.5.5.jar").start();
            Thread.sleep(1000);
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }

    private String endpoint;
    private Response response;

    @When("I send a POST request to {string} using title: {string} and description: {string}")
    public void postToDo(String endpoint, String title, String description) {
        this.endpoint = endpoint;
        String JsonParams = "{\"title\": \"" + title + "\", \"description\": \"" + description + "\"}";
        response = given()
                .contentType("application/json")
                .body(JsonParams)
                .when()
                .post(this.endpoint);
    }

    @Then("I should receive a response status code of {int}")
    public void verifyStatusCode(int statusCode) {
        response.then()
                .statusCode(statusCode);
    }

    @And("the response should have a todo task with title: {string} and description: {string}")
    public void verifyToDoResponseParams(String title, String description) {
        response.then()
                .body("title", equalTo(title))
                .body("description", equalTo(description));
    }

    @When("I send a POST request to {string} with title {string} and description {string}")
    public void postProject(String endpoint, String title, String description) {
        this.endpoint = endpoint;
        String JsonParams = "{\"title\": \"" + title + "\", \"description\": \"" + description + "\"}";
        response = given()
                .contentType("application/json")
                .body(JsonParams)
                .when()
                .post(this.endpoint);
    }

    @And("the response should contain a project with title {string} and description {string}")
    public void verifyProjectResponseParams(String title, String description) {
        response.then()
                .body("title", equalTo(title))
                .body("description", equalTo(description));
    }

    @Given("a project with the title {string} already exists")
    public void projectWithTitleExists(String title) {
        endpoint = "/projects";
        String projectJsonParams = "{\"title\": \"" + title + "\", \"description\": \"Autogenerated project\"}";
        Response postResponse = given()
                .contentType("application/json")
                .body(projectJsonParams)
                .when()
                .post(endpoint)
                .then()
                .statusCode(201)
                .extract()
                .response();

        projectId = postResponse.path("id");
    }

    @When("I send a POST request to {string} with id {string} and title {string} and description {string}")
    public void postProjectWithSpecifiedId(String endpoint, String id, String title, String description) {
        String projectJsonParams = "{\"id\": \"" + id + "\", \"title\": \"" + title + "\", \"description\": \"" + description + "\"}";
        response = given()
                .contentType("application/json")
                .body(projectJsonParams)
                .when()
                .post(endpoint);
    }

    @And("the response should contain the error message {string}")
    public void verifyErrorMessage(String errorMessage) {
        String responseBody = response.asString();
        assertTrue(responseBody.contains(errorMessage));
    }

    @When("I send a PUT request to {string} using title: {string} and description: {string}")
    public void putToDo(String endpoint, String title, String description) {
        this.endpoint = endpoint;
        String JsonParams = "{\"title\": \"" + title + "\", \"description\": \"" + description + "\"}";
        response = given()
                .contentType("application/json")
                .body(JsonParams)
                .when()
                .put(this.endpoint);
    }

    @When("I send a PUT request to {string} with active {string}")
    public void putProjectActive(String endpoint, String activeOrNot) {
        this.endpoint = endpoint;
        String projectJsonParams = "\"active\": \"" + activeOrNot + "\"}";
        response = given()
                .contentType("application/json")
                .body(projectJsonParams)
                .when()
                .put(this.endpoint);
    }

    @When("I send a PUT request to {string} with title {string} and description {string}")
    public void putProject(String endpoint, String title, String description) {
        this.endpoint = endpoint;
        String projectJsonParams = "{\"title\": \"" + title + "\", \"description\": \"" + description + "\"}";
        response = given()
                .contentType("application/json")
                .body(projectJsonParams)
                .when()
                .put(this.endpoint);
    }

    @When("I send a DELETE request to {string}")
    public void deleteToDoOrProject(String endpoint) {
        this.endpoint = endpoint;
        response = given()
                .contentType("application/json")
                .when()
                .delete(this.endpoint);
    }

    @And("the todo at {string} should be deleted")
    public void verifyDeletedToDo(String endpoint) {
        this.endpoint = endpoint;
        response = given()
                .contentType("application/json")
                .when()
                .delete(this.endpoint);

        response.then()
                .statusCode(404);
    }

    @And("the project at {string} should be deleted")
    public void verifyDeletedProject(String endpoint) {
        this.endpoint = endpoint;
        response = given()
                .contentType("application/json")
                .when()
                .delete(this.endpoint);

        response.then()
                .statusCode(404);
    }

    @When("I send a GET request to {string}")
    public void getToDoOrProject(String endpoint) {
        this.endpoint = endpoint;
        response = given()
                .contentType("application/json")
                .when()
                .get(this.endpoint);
    }

    @When("I send a GET request to {string} using filter {string}")
    public void getToDoOrProjectUsingFilter(String endpoint, String filter) {
        this.endpoint = endpoint;
        response = given()
                .queryParam("title", filter)
                .when()
                .get(this.endpoint);
    }

    @And("I should receive a list of projects with {string}")
    public void getListOfProjects(String title) {
        response.then().body("projects.title", hasItem(title));
    }

    @And("the response should contain a list of todos")
    public void verifyListOfTodos() {
        response.then()
                .body("size()", greaterThan(0));
    }
    @And("I should receive an empty list of projects")
    public void getListOfProjectsEmpty() {
        response.then().body("projects", hasSize(0));
    }
}
